// GENERATED by scripts/bundle-skills.mjs — do not edit by hand.
// Edit the SKILL.md files under packages/convex/skills/ and re-run
// `bun run --filter '@aqsha/convex' skills:bundle`. Convex functions cannot read
// the filesystem at runtime, so the builtin skills are inlined here for seeding.

export type BuiltinSkillResource = {
  path: string;
  kind: "reference" | "asset" | "script";
  content: string;
};

export type BuiltinSkill = {
  slug: string;
  doc: string;
  resources: BuiltinSkillResource[];
};

export const BUILTIN_SKILLS: readonly BuiltinSkill[] = [
  {
    "slug": "academic-id",
    "doc": "---\nname: academic-id\ndescription: \"Register dan konvensi bahasa akademik Indonesia: ragam formal, istilah baku, dan struktur argumen ilmiah. Gunakan saat menulis atau menyunting teks akademik berbahasa Indonesia.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Ragam bahasa\nGunakan ragam formal: hindari bentuk lisan dan singkatan tidak baku. Pakai istilah baku KBBI; serapan asing dimiringkan bila belum diserap. Kalimat efektif, satu gagasan utama per paragraf.\n\n## Struktur argumen\nPola: pernyataan -> dukungan bukti/sitasi -> interpretasi -> kaitan ke argumen besar. Batas klaim eksplisit; bedakan temuan dari opini.\n\n## Sitasi\nKlaim empiris wajib bersumber. Tandai bagian yang membutuhkan rujukan sebagai [perlu sumber], jangan mengarang nama peneliti atau angka.\n",
    "resources": []
  },
  {
    "slug": "citation-apa7",
    "doc": "---\nname: citation-apa7\ndescription: \"Konvensi sitasi dan daftar pustaka gaya APA 7th edition (in-text dan referensi). Gunakan saat menyusun atau memeriksa format sitasi APA pada tulisan akademik.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## In-text\nFormat penulis-tahun: (Vaswani et al., 2017). Kutipan langsung sertakan halaman: (Smith, 2020, p. 12). Tiga penulis atau lebih gunakan \"et al.\" sejak kutipan pertama.\n\n## Daftar referensi\nUrut alfabetis berdasarkan nama belakang penulis pertama. Pola artikel jurnal: Penulis, A. A., & Penulis, B. B. (Tahun). Judul artikel. *Nama Jurnal, Volume*(Nomor), halaman. https://doi.org/xxxx\n\n## Catatan\nSertakan DOI sebagai URL penuh bila ada. Jangan mengarang entri — tandai sebagai [perlu sumber] bila referensi belum terverifikasi.\n",
    "resources": []
  },
  {
    "slug": "citation-verification",
    "doc": "---\nname: citation-verification\ndescription: \"Resep verifikasi sitasi 4-langkah (eksistensi, konsistensi metadata, validitas DOI/arXiv, aksesibilitas). Gunakan saat memeriksa apakah sitasi/daftar pustaka sebuah dokumen valid dan tidak fabrikasi.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Langkah\n1. Eksistensi: cocokkan judul+penulis ke basis data akademik (OpenAlex/Crossref).\n2. Konsistensi metadata: bandingkan penulis/tahun/venue yang dikutip vs record.\n3. Identifier: resolve DOI (Crossref) dan arXiv ID; cocokkan judulnya.\n4. Aksesibilitas: URL mati hanya menurunkan aksesibilitas, bukan validitas — langkah 1-3 yang menentukan.\n\n## Penyajian\nPenanda bukan tuduhan: bisa karena salah ketik metadata, basis data tidak lengkap, atau gangguan penyedia. Anjurkan verifikasi manual untuk item yang ditandai.\n",
    "resources": []
  },
  {
    "slug": "deep-research-cs-ml",
    "doc": "---\nname: deep-research-cs-ml\ndescription: \"Metodologi deep research bidang computer science/machine learning: disiplin benchmark dan SOTA, ablation dan reproducibility, pembobotan preprint, serta kewaspadaan terhadap leaderboard. Gunakan untuk pertanyaan riset CS/ML lintas sumber.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Benchmark dan SOTA\nKlaim \"state-of-the-art\" harus disertai benchmark, split data, dan metrik yang sama persis dengan pembanding. Waspadai cherry-picking metrik dan perbandingan tidak apple-to-apple (beda ukuran model, data pretraining, atau anggaran komputasi).\n\n## Reproducibility dan ablation\nUtamakan makalah dengan kode + checkpoint terbuka dan studi ablation yang mengisolasi kontribusi tiap komponen. Tanpa ablation, atribusi peningkatan ke ide inti lemah. Catat seed, varians antar-run, dan apakah hasil rata-rata atau best-of-N.\n\n## Pembobotan preprint\narXiv/preprint diberi bobot lebih rendah dan ditandai eksplisit sampai ada peer-review (NeurIPS/ICML/ICLR/ACL/CVPR dst.). Bedakan klaim yang sudah direplikasi komunitas dari klaim baru yang belum diuji ulang.\n\n## Kewaspadaan leaderboard\nLeaderboard publik rawan overfitting ke test set dan kontaminasi data (test set bocor ke pretraining). Periksa tanggal rilis benchmark vs. tanggal pelatihan model. Nyatakan batas generalisasi di luar distribusi benchmark.\n",
    "resources": []
  },
  {
    "slug": "deep-research-guide",
    "doc": "---\nname: deep-research-guide\ndescription: \"Metodologi umum deep research berbasis sumber: strategi pencarian bertingkat, kriteria kecukupan bukti, dan struktur laporan. Gunakan untuk pertanyaan riset lintas bidang yang butuh sintesis dari banyak sumber.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Strategi sumber\nBangun bucket bertingkat: (1) tinjauan sistematis/meta-analisis, (2) studi primer peer-review, (3) sumber otoritatif (badan resmi/standar), (4) konteks web mutakhir. Beri bobot rendah pada preprint dan tandai eksplisit.\n\n## Kecukupan bukti\nLanjutkan ronde pencarian sampai klaim inti didukung minimal dua sumber independen dan celah utama tertutup. Jika bukti tetap tipis, nyatakan ketidakpastian alih-alih memaksakan kesimpulan.\n\n## Sintesis & pelaporan\nSusun: ringkasan temuan, bukti per-klaim dengan sitasi, keterbatasan, dan pertanyaan terbuka. Klaim faktual tanpa sumber pendukung ditulis sebagai hipotesis atau dihapus.\n",
    "resources": []
  },
  {
    "slug": "deep-research-medis",
    "doc": "---\nname: deep-research-medis\ndescription: \"Metodologi deep research bidang kedokteran/kesehatan: skrining PRISMA, hierarki bukti (meta-analisis > RCT > kohort > kasus-kontrol), serta penandaan retraction dan jurnal predator. Gunakan untuk pertanyaan riset klinis/biomedis yang butuh sintesis bukti.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Hierarki bukti\nBobotkan sumber sesuai desain studi: tinjauan sistematis/meta-analisis > uji acak terkendali (RCT) > studi kohort > kasus-kontrol > seri kasus > opini ahli. Untuk klaim efikasi intervensi, utamakan RCT dan meta-analisis; kohort hanya untuk paparan/prognosis bila RCT tidak etis/feasible.\n\n## Skrining PRISMA\nLacak alur identifikasi → penyaringan → kelayakan → inklusi. Catat kriteria inklusi/eksklusi eksplisit (populasi, intervensi, pembanding, luaran — PICO). Nyatakan jumlah studi pada tiap tahap agar sintesis dapat ditelusuri.\n\n## Tanda bahaya\nTandai eksplisit: artikel yang sudah di-retraction (cek Retraction Watch/PubPed), jurnal predator (tidak terindeks, biaya proses cepat tanpa peer-review nyata), konflik kepentingan pendanaan industri, dan ukuran sampel sangat kecil. Diskrepansi statistik atau heterogenitas tinggi (I² besar) diberi catatan, bukan dibuang.\n\n## Interpretasi\nBedakan signifikansi statistik dari relevansi klinis (effect size, NNT/NNH, interval kepercayaan). Jangan ekstrapolasi temuan in-vitro/hewan ke manusia tanpa kualifikasi. Nyatakan ketidakpastian bila bukti tipis alih-alih memaksakan rekomendasi klinis.\n",
    "resources": []
  },
  {
    "slug": "deep-research-pendidikan",
    "doc": "---\nname: deep-research-pendidikan\ndescription: \"Metodologi deep research bidang pendidikan: hierarki desain studi, kehati-hatian effect size dan ukuran sampel, serta batas transfer konteks. Gunakan untuk pertanyaan riset pendidikan/pembelajaran yang butuh sintesis bukti lintas konteks.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Hierarki desain studi\nBobotkan: meta-analisis/tinjauan sistematis > eksperimen acak (RCT pendidikan) > kuasi-eksperimen (dengan kelompok pembanding) > korelasional > studi kasus/kualitatif. Untuk klaim efektivitas intervensi pembelajaran, utamakan desain dengan kelompok kontrol.\n\n## Effect size dan sampel\nLaporkan effect size (Cohen's d, Hedges' g) bukan sekadar signifikansi. Waspadai sampel kecil dan unit analisis yang salah (siswa vs. kelas vs. sekolah — perhatikan clustering/efek desain). Hasil dari satu kelas/sekolah tidak digeneralisasi tanpa kualifikasi.\n\n## Batas transfer konteks\nTemuan pendidikan sangat bergantung konteks (kurikulum, budaya, bahasa, tingkat sumber daya). Intervensi yang berhasil di satu sistem belum tentu transfer ke konteks Indonesia. Nyatakan asumsi konteks secara eksplisit.\n\n## Interpretasi\nBedakan luaran proksi (skor tes jangka pendek) dari luaran bermakna (retensi, transfer, hasil jangka panjang). Hindari klaim kausal dari desain korelasional; tandai bias publikasi bila hanya hasil positif yang tersedia.\n",
    "resources": []
  },
  {
    "slug": "stat-verification",
    "doc": "---\nname: stat-verification\ndescription: \"Resep verifikasi statistik: kapan statcheck/GRIM/power applicable, ambang toleransi pembulatan, dan interpretasi yang jujur. Gunakan saat memeriksa konsistensi angka statistik (p-value, mean/SD, power) sebuah paper.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Kapan berlaku\nstatcheck hanya untuk pelaporan NHST gaya APA (t, F, r, chi-square, z). GRIM/GRIMMER untuk mean/SD pada skala integer dengan N kecil. Power analysis bersifat prospektif (effect size + N), bukan post-hoc.\n\n## Interpretasi\nDiskrepansi angka BUKAN tuduhan fraud. Penyebab umum: pembulatan, salah ketik, koreksi tidak dilaporkan, uji satu-arah, atau artefak ekstraksi teks. Hanya perbedaan keputusan signifikansi (melewati ambang) yang naik ke \"perlu ditinjau\".\n\n## Pelaporan\nSelalu tautkan hasil recompute agar dapat diperiksa ulang, sebutkan batas cakupan, dan gunakan bahasa netral.\n",
    "resources": []
  }
];

// Raw SKILL.md documents, in catalog order (back-compat for the seed path).
export const BUILTIN_SKILL_DOCS: readonly string[] = BUILTIN_SKILLS.map(
  (skill) => skill.doc,
);
