// GENERATED by scripts/bundle-skills.mjs — do not edit by hand.
// Edit the SKILL.md files under packages/convex/skills/ and re-run
// `bun run --filter '@aqsha/convex' skills:bundle`. Convex functions cannot read
// the filesystem at runtime, so the builtin skills are inlined here for seeding.

export type BuiltinSkillResource = {
  path: string;
  kind: "reference" | "asset" | "script";
  content: string;
};

export type BuiltinSkill = {
  slug: string;
  doc: string;
  resources: BuiltinSkillResource[];
};

export const BUILTIN_SKILLS: readonly BuiltinSkill[] = [
  {
    "slug": "academic-id",
    "doc": "---\nname: academic-id\ndescription: \"Register dan konvensi bahasa akademik Indonesia: ragam formal, istilah baku, dan struktur argumen ilmiah. Gunakan saat menulis atau menyunting teks akademik berbahasa Indonesia.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Ragam bahasa\nGunakan ragam formal: hindari bentuk lisan dan singkatan tidak baku. Pakai istilah baku KBBI; serapan asing dimiringkan bila belum diserap. Kalimat efektif, satu gagasan utama per paragraf.\n\n## Struktur argumen\nPola: pernyataan -> dukungan bukti/sitasi -> interpretasi -> kaitan ke argumen besar. Batas klaim eksplisit; bedakan temuan dari opini.\n\n## Sitasi\nKlaim empiris wajib bersumber. Tandai bagian yang membutuhkan rujukan sebagai [perlu sumber], jangan mengarang nama peneliti atau angka.\n",
    "resources": []
  },
  {
    "slug": "citation-apa7",
    "doc": "---\nname: citation-apa7\ndescription: \"Konvensi sitasi dan daftar pustaka gaya APA 7th edition (in-text dan referensi). Gunakan saat menyusun atau memeriksa format sitasi APA pada tulisan akademik.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## In-text\nFormat penulis-tahun: (Vaswani et al., 2017). Kutipan langsung sertakan halaman: (Smith, 2020, p. 12). Tiga penulis atau lebih gunakan \"et al.\" sejak kutipan pertama.\n\n## Daftar referensi\nUrut alfabetis berdasarkan nama belakang penulis pertama. Pola artikel jurnal: Penulis, A. A., & Penulis, B. B. (Tahun). Judul artikel. *Nama Jurnal, Volume*(Nomor), halaman. https://doi.org/xxxx\n\n## Catatan\nSertakan DOI sebagai URL penuh bila ada. Jangan mengarang entri — tandai sebagai [perlu sumber] bila referensi belum terverifikasi.\n",
    "resources": []
  },
  {
    "slug": "citation-verification",
    "doc": "---\nname: citation-verification\ndescription: \"Resep verifikasi sitasi 4-langkah (eksistensi, konsistensi metadata, validitas DOI/arXiv, aksesibilitas). Gunakan saat memeriksa apakah sitasi/daftar pustaka sebuah dokumen valid dan tidak fabrikasi.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Langkah\n1. Eksistensi: cocokkan judul+penulis ke basis data akademik (OpenAlex/Crossref).\n2. Konsistensi metadata: bandingkan penulis/tahun/venue yang dikutip vs record.\n3. Identifier: resolve DOI (Crossref) dan arXiv ID; cocokkan judulnya.\n4. Aksesibilitas: URL mati hanya menurunkan aksesibilitas, bukan validitas — langkah 1-3 yang menentukan.\n\n## Penyajian\nPenanda bukan tuduhan: bisa karena salah ketik metadata, basis data tidak lengkap, atau gangguan penyedia. Anjurkan verifikasi manual untuk item yang ditandai.\n",
    "resources": []
  },
  {
    "slug": "deep-research-guide",
    "doc": "---\nname: deep-research-guide\ndescription: \"Metodologi umum deep research berbasis sumber: strategi pencarian bertingkat, kriteria kecukupan bukti, dan struktur laporan. Gunakan untuk pertanyaan riset lintas bidang yang butuh sintesis dari banyak sumber.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Strategi sumber\nBangun bucket bertingkat: (1) tinjauan sistematis/meta-analisis, (2) studi primer peer-review, (3) sumber otoritatif (badan resmi/standar), (4) konteks web mutakhir. Beri bobot rendah pada preprint dan tandai eksplisit.\n\n## Kecukupan bukti\nLanjutkan ronde pencarian sampai klaim inti didukung minimal dua sumber independen dan celah utama tertutup. Jika bukti tetap tipis, nyatakan ketidakpastian alih-alih memaksakan kesimpulan.\n\n## Sintesis & pelaporan\nSusun: ringkasan temuan, bukti per-klaim dengan sitasi, keterbatasan, dan pertanyaan terbuka. Klaim faktual tanpa sumber pendukung ditulis sebagai hipotesis atau dihapus.\n",
    "resources": []
  },
  {
    "slug": "stat-verification",
    "doc": "---\nname: stat-verification\ndescription: \"Resep verifikasi statistik: kapan statcheck/GRIM/power applicable, ambang toleransi pembulatan, dan interpretasi yang jujur. Gunakan saat memeriksa konsistensi angka statistik (p-value, mean/SD, power) sebuah paper.\"\nlicense: Proprietary\nmetadata: { author: aqsha, version: \"1.0\", scope: builtin }\n---\n## Kapan berlaku\nstatcheck hanya untuk pelaporan NHST gaya APA (t, F, r, chi-square, z). GRIM/GRIMMER untuk mean/SD pada skala integer dengan N kecil. Power analysis bersifat prospektif (effect size + N), bukan post-hoc.\n\n## Interpretasi\nDiskrepansi angka BUKAN tuduhan fraud. Penyebab umum: pembulatan, salah ketik, koreksi tidak dilaporkan, uji satu-arah, atau artefak ekstraksi teks. Hanya perbedaan keputusan signifikansi (melewati ambang) yang naik ke \"perlu ditinjau\".\n\n## Pelaporan\nSelalu tautkan hasil recompute agar dapat diperiksa ulang, sebutkan batas cakupan, dan gunakan bahasa netral.\n",
    "resources": []
  }
];

// Raw SKILL.md documents, in catalog order (back-compat for the seed path).
export const BUILTIN_SKILL_DOCS: readonly string[] = BUILTIN_SKILLS.map(
  (skill) => skill.doc,
);
